### ISSUE TITLE
v1.0.3 install fails because of node version mismatch

### ISSUE THREAD

**Issue by bashFish** [s-h-a-d-o-w/alfc#2]
honestly, just had no idea how to actually contact u ^^"

so works for me too, much love, made my day after almost resignation ^^"!

i have win 11, aorus 15p yd

v1.0.3 fails tho:

PS C:\Users\brdei\Documents\alfc> .\install.bat
Installing...
Error: Command failed: node C:\Users\brdei\Documents\alfc install-as-sudo
C:\Users\brdei\Documents\alfc\index.js:4357
    throw error;
    ^

Error: The module '\\?\C:\Users\brdei\Documents\alfc\build\Release\service.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.253 (C:\Users\brdei\Documents\alfc\index.js:812:18)
    at __webpack_require__ (C:\Users\brdei\Documents\alfc\index.js:24:31)
    at getServiceWrap (C:\Users\brdei\Documents\alfc\index.js:2443:17)
    at Object.add (C:\Users\brdei\Documents\alfc\index.js:2515:4)
    at Object.932 (C:\Users\brdei\Documents\alfc\index.js:4382:13)

    at C:\Users\brdei\Documents\alfc\index.js:3350:25
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  code: 1

**Comment by s-h-a-d-o-w** [comment]
Thanks a lot for reporting this, made me realize a quite essential mistake!

It’s fixed in v1.0.4. 🙂 

I’m also glad to hear you’ve been enjoying alfc!
