### ISSUE TITLE
me again ^^"

### ISSUE THREAD

**Issue by bashFish** [s-h-a-d-o-w/alfc#4]
hi ehr me again. so 1.0.4 doesn't work for me :/ 

tried to compile the master on windows 11 myself, there i had to adjust package.json -> index.js instead of ts or i would throw errors

so in theory build did work,
opening localhost:5522 after running install.bat or just run.bat actually never did the trick for me, even with firewall deactived. a dummy nodejs hello world app on port 1337 does open in browser.
so my biggest issue right now :  i got another black screen of death under load as the fan curve aborts at some point, again ^^" 
could you maybe add a few other points and recompile it ^^"? like [[40, 15], [50, 30], [70, 50], [80, 80], [88, 90]],

update:
btw: from what i read in other threads, below 25% is always mapped to "fan off". so thats' maybe why i always get a quite jumpy behavior between off / extremely on when e.g. gaming

**Comment by bashFish** [comment]
okay deeply confused over here (also not really into nodejs)

wenn i use node14.18.2 to compile the stuff i get that error of the other day again 
Error: The module '\\?\C:\Users\brdei\Documents\alfc-master\dist\build\Release\service.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.253 (C:\Users\brdei\Documents\alfc-master\dist\index.js:812:18)
    at __webpack_require__ (C:\Users\brdei\Documents\alfc-master\dist\index.js:24:31)
    at getServiceWrap (C:\Users\brdei\Documents\alfc-master\dist\index.js:2443:17)
    at Object.run (C:\Users\brdei\Documents\alfc-master\dist\index.js:2735:3)
    at Object.932 (C:\Users\brdei\Documents\alfc-master\dist\index.js:4432:13) {
  code: 'ERR_DLOPEN_FAILED'


when i use 16.13.1
i get "You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge"

also i figured in server/index.js, that it's only going up to version 14 in "versionMap"
:/

**Comment by s-h-a-d-o-w** [comment]
Please use the v1.0.4 release to run uninstall, then install again and paste its output here.
